[general]
live_config_reload = true


[window]
title = "Terminal"
dynamic_title = false
option_as_alt = "OnlyLeft"


[scrolling]
history = 0
multiplier = 0

[font]
size = 14.5

[font.offset]
x = 0
y = 2

[font.normal]
family = "CommitMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "CommitMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "CommitMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "CommitMono Nerd Font Mono"
style = "Bold Italic"

[cursor]
style.shape = "Beam"
style.blinking = "Always"

[selection]
save_to_clipboard = false


[terminal]
shell = { program = "zsh", args = ["-l", "-c", "zellij attach -c main"] }


[env]
EDITOR = "hx"
CLICOLOR = "1"


[keyboard]
bindings = [
    { key = "C", mods = "Command", action = "ReceiveChar" },
    { key = "Return", mods = "Shift", chars = "\u001B\r" },
]
