[general]
live_config_reload = false


[window]
title = "Terminal"
dynamic_title = true
opacity = 0.9
blur = true
option_as_alt = "OnlyLeft"


[scrolling] # tmux handles scrolling
history = 0
multiplier = 0

[font]
normal.family = "Fira Code"
size = 14.5


[cursor]
style.shape = "Beam"
style.blinking = "Always"

[selection]
save_to_clipboard = false


[terminal]
# shell = { program = "zsh", args = ["-l"]}
shell = { program = "zsh", args = ["-l", "-c", "tmux new -t main"] }

[env]
EDITOR = "hx"
CLICOLOR = "1"
