[[language]]
name = "rust"
formatter = { command = "rustfmt" }
language-servers = ["rust-analyzer", "harper-ls", "fs_watcher_lsp"]

[language-server.rust-analyzer.config]
files.watcher = "server"

[[language]]
name = "c"
language-servers = ["clangd", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "cpp"
language-servers = ["clangd", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "c-sharp"
language-servers = ["roslyn-language-server", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "go"
language-servers = ["gopls", "golangci-lint-lsp", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "python"
language-servers = ["ty", "ruff", "jedi", "pylsp", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "javascript"
language-servers = ["typescript-language-server", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "jsx"
language-servers = ["typescript-language-server", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "typescript"
language-servers = ["typescript-language-server", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "tsx"
language-servers = ["typescript-language-server", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "java"
language-servers = ["jdtls", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "kotlin"
language-servers = ["kotlin-language-server", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "scala"
language-servers = ["metals", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "ruby"
language-servers = ["ruby-lsp", "solargraph", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "php"
language-servers = ["intelephense", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "swift"
language-servers = ["sourcekit-lsp", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "dart"
language-servers = ["dart", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "haskell"
language-servers = ["haskell-language-server", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "lua"
language-servers = ["lua-language-server", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "bash"
language-servers = ["bash-language-server", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "nix"
language-servers = ["nil", "nixd", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "clojure"
language-servers = ["clojure-lsp", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "cmake"
language-servers = ["neocmakelsp", "cmake-language-server", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
language-servers = ["taplo", "tombi", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "superhtml", "harper-ls", "fs_watcher_lsp"]

[[language]]
auto-format = true
name = "markdown"
language-servers = ["markdown-oxide", "rumdl", "harper-ls", "mpls", "fs_watcher_lsp"]
comment-tokens = ["-", "+", "*", "- [ ]", ">"]

[[language]]
name = "text"
scope = "text.plain"
file-types = ["txt"]
language-servers = ["harper-ls", "fs_watcher_lsp"]

[[language]]
name = "git-commit"
language-servers = ["commit-lsp", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "solidity"
language-servers = ["solc", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "typst"
language-servers = ["tinymist", "harper-ls", "fs_watcher_lsp"]

[[language]]
name = "ink"
language-servers = ["harper-ls", "fs_watcher_lsp"]

[[language]]
name = "org"
language-servers = ["harper-ls", "fs_watcher_lsp"]

[[language]]
name = "mail"
language-servers = ["harper-ls", "fs_watcher_lsp"]

[[language]]
name = "sql"
language-servers = ["sql-language-server", "fs_watcher_lsp"]
formatter = { command = "sql-formatter" }

[[language]]
name = "jinja"
language-servers = [
  "jinja-lsp",
  "vscode-html-language-server",
  "superhtml",
  "tailwindcss-ls",
  "harper-ls",
  "fs_watcher_lsp"
]

[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

[language-server.taplo]
config = {} # https://github.com/helix-editor/helix/issues/3897#issuecomment-2889068677

[language-server.bash-language-server]
config = { bashIde = { enableSourceErrorDiagnostics = true, shfmt = { simplifyCode = true } } }

[language-server.docker-compose-langserver]
config = { telemetry = { enableTelemetry = false } }

[language-server.jinja-lsp]
command = "jinja-lsp"

[language-server.harper-ls]
config.harper-ls.diagnosticSeverity = "hint"
config.harper-ls.dialect = "British"
config.harper-ls.linters.SpellCheck = true
config.harper-ls.linters.SpelledNumbers = false
config.harper-ls.linters.AnA = true
config.harper-ls.linters.SentenceCapitalization = true
config.harper-ls.linters.UnclosedQuotes = true
config.harper-ls.linters.WrongQuotes = false
config.harper-ls.linters.LongSentences = true
config.harper-ls.linters.RepeatedWords = true
config.harper-ls.linters.Spaces = true
config.harper-ls.linters.Matcher = true
config.harper-ls.linters.CorrectNumberSuffix = true
config.harper-ls.codeActions.ForceStable = false
config.harper-ls.markdown.IgnoreLinkTitle = false

[language-server.mpls]
command = "mpls"
args = ["--enable-emoji", "--enable-wikilinks", "--enable-footnotes"]

[language-server.fs_watcher_lsp]
command = "fs_watcher_lsp"

[language-server.tofu-ls]
command = "tofu-ls"
args = ["serve"]

[[language]]
name = "hcl"
language-servers = ["tofu-ls", "fs_watcher_lsp"]

[[language]]
name = "tfvars"
language-servers = ["tofu-ls", "fs_watcher_lsp"]
