#!/usr/bin/env bash
# -*- mode: shell-script -*-
#
# Tangle .org files with org-mode
# Example usage:
#    ∴ tangle nested-in-all.org
#    Files:  "nested-in-all.org", Dir: /Users/hinmanm/es-scripts
#    Tangled 6 code blocks from nested-in-all.org


for file in $@; do
	emacs -q -nw --batch --eval "(require 'org)" --eval "(org-babel-tangle-file \"$file\")"
done




# (progn
#   (require 'org)
#   (find-file (expand-file-name \"$file\" \"$DIR\"))
#   (org-babel-tangle \"$file\")
#   (kill-buffer))" 2>&1 | grep "Tangled"



# emacs -nwq --batch --eval "(require 'org)" --eval '(org-babel-tangle-file "file-to-tangle.org")'
