## My zsh.
## ~/.zshrc
## 26 Sept 2022

# Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# GPG
export GPG_TTY=$(tty)

# PATH
PATH=$PATH:~/.cargo/bin
PATH=$PATH:~/.dotnet/tools
PATH=$PATH:/usr/local/share/dotnet
PATH=$PATH:/opt/homebrew/opt/gnu-sed/libexec/gnubin
PATH=$PATH:~/Projects/Local/Bin/omnisharp
PATH=$PATH:~/Projects/Local/Bin/netcoredbg


# Bindings
bindkey "^[[1;3A" history-beginning-search-backward
bindkey "^[[1;3B" history-beginning-search-forward
bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word


# History
HISTSIZE=10000000
SAVEHIST=$HISTSIZE
LESSHISTFILE=-

setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt inc_append_history
setopt hist_reduce_blanks

# Other
export DOTNET_CLI_TELEMETRY_OPTOUT=1

# Alias
alias awslocal="aws --endpoint-url http://localhost:4566"
alias trigger-ci="git commit --allow-empty -m 'Trigger CI/CD - Empty commit'"

# Avoid customizations for dumb terminals
if [[ "$TERM" != "dumb" ]] then

   TERM=alacritty

   FPATH=$HOMEBREW_PREFIX/share/zsh-completions:$FPATH
   autoload bashcompinit && bashcompinit
   autoload -Uz compinit && compinit # Fix insecure files if need with: compaudit | xargs chmod g-w
   complete -C $HOMEBREW_PREFIX/bin/aws_completer aws

   # Plugins
   source $HOMEBREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh
   source $HOMEBREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
   eval "$(starship init zsh)"

fi


# Load eshell integration
[ -n "$EAT_SHELL_INTEGRATION_DIR" ] && source "$EAT_SHELL_INTEGRATION_DIR/zsh"



# Load extra
source ~/.config/zsh/priv.personal.zsh
source ~/.config/zsh/priv.work.zsh
